### PR TITLE
Convert to gradle, switch to opensimplex noise.

### PR DESCRIPTION
**Pull request by Baughn**
It builds and runs, server and client. I'm currently installing Optifine so I can get a better view of the world, because this terrain is monumental!

I doubt it'll work with your editor workspace as-is, but that should be a relatively simple fix; 'gradle idea' works, and I presume so would 'gradle eclipse'.

### CODE REVIEW

**Comment by Baughn** [comment]
I don't really see it. Can you point at a particular problem?

I figured out why dynmap wasn't rendering both sides of the map, though, so I'll have a side-by-side comparison tomorrow. Meanwhile, have https://www.brage.info/rwg/comparison/ for two screenshots; the older one is with OS, but I think they look about the same. (It's hard to be sure without a larger sample.)

**Comment by Baughn** [comment]
...you're right, actually. Interesting; that shouldn't happen. Let me take another look at this algorithm.

**Comment by Baughn** [comment]
I think I figured it out. It's a scaling problem; the OpenSimplex code produces a larger range of values than the Perlin code. So I changed the scaling factors to make the output match.

I can no longer tell the difference. http://goo.gl/DyHVok has a combination map, with the left-hand square being OpenSimplex and the right-hand Perlin. (Although I messed up the intersection, and there's a smaller square of OS mapspace on the right-hand side, so look for the lines.)

Is it actually better, map-wise? Well... maybe. It does feel a little less predictable, but that could be a placebo effect; honestly, they're just really similar.

**Comment by ted80** [comment]
i'd rather stick to perlin noise

Perlin 2D .......   3 ns
Perlin 3D .......  32 ns
Perlin 4D ....... 183 ns
Simplectic 2D ...   3 ns
Simplectic 3D ...  35 ns
Simplectic 4D ...  48 ns
OpenSimplex 2D ..   4 ns
OpenSimplex 3D ..  78 ns

**Comment by Baughn** [comment]
It's a bit slower. I didn't notice the slowdown while playing, but fair enough; I'd rather see you finish your work, before going ahead and trying a full-mod benchmark. Besides, I've gotten a few ideas of my own that I want to try.

I'll probably throw a Gradle conversion patch your way, though.

**Pull request closed without merging**
